# Generated by Django 6.0.1 on 2026-01-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_hirerequest_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hirerequest',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hirerequest',
            old_name='contact_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='hirerequest',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='hirerequest',
            name='question',
        ),
    ]
