# Generated by Django 6.0.1 on 2026-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_full_name_hirerequest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerequest',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
