# Generated by Django 6.0.1 on 2026-02-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_softskill_skill_icon_url_alter_skill_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='short_desc',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Framework', 'Framework'), ('Database', 'Database'), ('Networking', 'Networking'), ('IT Support', 'IT Support'), ('Soft Skill', 'Soft Skill')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
